// This file is automatically generated.
// Please do not change this file!
export const colorBlack: string;
export const colorBlue: string;
export const colorGrey: string;
export const multilineTruncate: string;
export const typography: string;
