// This file is automatically generated.
// Please do not change this file!
export const videoAuthor: string;
export const videoCard: string;
export const videoCardFooter: string;
export const videoCardThumbnail: string;
export const videoLink: string;
export const videoPublishedAt: string;
export const videoViews: string;
