name: deploy-appbar

on:
  push:
    branches:
      - main
    paths:
      - 'appbar/**'
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/playwright.yml
    secrets: inherit

  build:
    needs: tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build with Docker
        run: |
          docker build \
            --target builder \
            --build-arg PRODUCTION_DOMAIN=${{ secrets.PRODUCTION_DOMAIN }} \
            -f appbar/Dockerfile \
            -t appbar-build .

      - name: Extract build artifacts
        run: |
          docker create --name temp-container appbar-build
          docker cp temp-container:/app/appbar/dist ./dist
          docker rm temp-container
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS S3
        run: |
          VERSION=$(docker run --rm appbar-build node -p "require('./package.json').version")
          aws s3 sync dist s3://${{ secrets.AWS_BUCKET_NAME }}/appbar/${VERSION} --delete
          aws s3 sync dist s3://${{ secrets.AWS_BUCKET_NAME }}/appbar/latest --delete

      - name: Invalidate CloudFront Distribution
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/appbar/latest/*"
